spring:
  jpa:
    generate-ddl: false
    hibernate:
  ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    dispatch-options-request: true

  datasource:
    url: jdbc:mysql://tenselite.cqiaew1yudy1.us-east-1.rds.amazonaws.com/tenselite?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
    username: admin
    password: Soccerplayer11
    hikari:
      initialization-fail-timeout: 0
      data-source-properties:
        cacheDefaultTimezone: false

  flyway:
    baselineOnMigrate: true
    locations: classpath:/db/migration